'use strict';
const { describe, it, before, after } = require('node:test');
const assert = require('node:assert/strict');
const fs = require('fs'), os = require('os'), path = require('path'), { spawn } = require('child_process');
const { DatabaseSync } = require('node:sqlite');
const { createServer } = require('../src/server'); const { signJwt } = require('../src/security');
const DATA = path.join(__dirname, '..', '..', 'tests', 'e2e-data'); const FIX = path.join(__dirname, '..', '..', 'tests');
const b64 = f => fs.readFileSync(f).toString('base64');
const newDir = () => fs.mkdtempSync(path.join(os.tmpdir(), 'ns-api-'));
const mk = (over = {}) => createServer({ dataDir: over.dataDir || newDir(), port: 0, logLevel: 'error', paceMs: 0, ...over });
async function client(app) { const a = await app.listen(); const base = `http://127.0.0.1:${a.port}`;
  const j = async (method, p, body, token, extra = {}) => { const r = await fetch(base + p, { method, headers: { ...(body !== undefined ? { 'Content-Type': 'application/json' } : {}), ...(token ? { Authorization: 'Bearer ' + token } : {}), ...(extra.headers || {}) }, body: body !== undefined ? (extra.rawBody || JSON.stringify(body)) : undefined }); const ct = r.headers.get('content-type') || ''; return { status: r.status, headers: r.headers, body: ct.includes('json') ? await r.json() : Buffer.from(await r.arrayBuffer()) }; };
  return { base, j }; }
const SIGN = (n, extra = {}) => ({ fullName: 'User ' + n, email: `u${n}@example.com`, phone: '+91 9876543210', password: 'password123', confirm: 'password123', role: 'LAWYER', ...extra });
async function signup(c, n) { const r = await c.j('POST', '/api/auth/signup', SIGN(n)); assert.equal(r.status, 201, JSON.stringify(r.body)); return { token: r.body.token, user: r.body.user }; }
async function waitDone(c, cid, token) { for (let i = 0; i < 200; i++) { const r = await c.j('GET', `/api/cases/${cid}/analysis`, undefined, token); if (r.body.analysis && r.body.analysis.status !== 'running') return r.body; await new Promise(r => setTimeout(r, 50)); } throw new Error('analysis did not finish'); }
async function seedCase(c, token, name = 'Depot incident review') { const cs = await c.j('POST', '/api/cases', { name, type: 'Criminal', jurisdiction: 'Chennai' }, token); assert.equal(cs.status, 201); const cid = cs.body.case.id;
  for (const f of ['PW-3 Statement.txt', 'PW-5 Statement.txt', 'CCTV Review Report.txt', 'Device Location Record.txt', 'Incident Report.txt', 'Written Submission.txt']) { const r = await c.j('POST', `/api/cases/${cid}/documents`, { filename: f, contentBase64: b64(path.join(DATA, f)) }, token); assert.equal(r.status, 201, JSON.stringify(r.body)); }
  const tr = await c.j('POST', `/api/cases/${cid}/transcripts`, { filename: 'Hearing 3 transcript.txt', contentBase64: b64(path.join(DATA, 'Hearing 3 transcript.txt')), hearingDate: '2026-03-20', hearingNumber: '3' }, token); assert.equal(tr.status, 201);
  return cid; }
async function seedAuthorities(c, token) { for (const a of JSON.parse(fs.readFileSync(path.join(DATA, 'authorities.json'), 'utf8'))) { const r = await c.j('POST', '/api/authorities', { ...a, kind: 'Judgment' }, token); assert.equal(r.status, 201, JSON.stringify(r.body)); } }

describe('health, transport and hardening', () => {
  let app, c; before(async () => { app = mk({ maxUploadBytes: 200000 }); c = await client(app); }); after(() => app.close());
  it('health is public and reports no secrets', async () => { const r = await c.j('GET', '/api/health'); assert.equal(r.status, 200); assert.equal(r.body.storage, 'sqlite'); assert.ok(!JSON.stringify(r.body).includes('key')); });
  it('sets security headers and serves the app with a CSP', async () => { const r = await fetch(c.base + '/'); assert.equal(r.status, 200); assert.match(r.headers.get('content-security-policy'), /connect-src 'self'/); assert.equal(r.headers.get('x-content-type-options'), 'nosniff'); assert.equal(r.headers.get('x-frame-options'), 'DENY'); });
  it('unknown route 404, wrong method 405, bad JSON 400 — all structured, no stack traces', async () => {
    const a = await c.j('GET', '/api/nope'); assert.equal(a.status, 404); assert.equal(a.body.error.code, 'NOT_FOUND'); const b = await c.j('DELETE', '/api/health'); assert.equal(b.status, 405);
    const d = await c.j('POST', '/api/auth/login', {}, null, { rawBody: '{oops' }); assert.equal(d.status, 400); assert.equal(d.body.error.code, 'BAD_JSON'); assert.ok(!JSON.stringify([a, b, d].map(x => x.body)).includes('at '), 'no stack frames'); });
  it('rejects oversized bodies', async () => { const r = await c.j('POST', '/api/auth/login', { email: 'x', password: 'y'.repeat(400000) }); assert.equal(r.status, 413); });
  it('requires JSON content type for bodies', async () => { const r = await fetch(c.base + '/api/auth/login', { method: 'POST', headers: { 'Content-Type': 'text/plain' }, body: 'x' }); assert.equal(r.status, 415); });
});

describe('authentication', () => {
  let app, c; before(async () => { app = mk({ loginMaxFailures: 3 }); c = await client(app); }); after(() => app.close());
  it('signup validates fields and never returns the password hash', async () => {
    const bad = await c.j('POST', '/api/auth/signup', { fullName: 'A', email: 'nope', phone: 'x', password: 'short', confirm: 'other', role: 'X' }); assert.equal(bad.status, 422); assert.ok(bad.body.error.errors.email && bad.body.error.errors.password && bad.body.error.errors.confirm && bad.body.error.errors.role);
    const ok = await c.j('POST', '/api/auth/signup', SIGN(1)); assert.equal(ok.status, 201); assert.ok(ok.body.token.split('.').length === 3); assert.ok(!JSON.stringify(ok.body).includes('passwordHash') && !JSON.stringify(ok.body).includes('pbkdf2'));
    const dup = await c.j('POST', '/api/auth/signup', SIGN(1)); assert.equal(dup.status, 422); assert.ok(dup.body.error.errors.email); });
  it('passwords are hashed in SQLite, never stored in plain text', async () => { const db = new DatabaseSync(app.cfg.dbFile); const r = db.prepare('SELECT password_hash FROM users WHERE email=?').get('u1@example.com'); assert.match(r.password_hash, /^pbkdf2\$/); assert.ok(!r.password_hash.includes('password123')); db.close(); });
  it('login error is generic for unknown email and wrong password', async () => { const a = await c.j('POST', '/api/auth/login', { email: 'ghost@example.com', password: 'password123' }); const b = await c.j('POST', '/api/auth/login', { email: 'u1@example.com', password: 'wrong-pass' }); assert.equal(a.status, 401); assert.equal(b.status, 401); assert.deepEqual(a.body, b.body); assert.equal(a.body.error.message, 'Invalid email or password.'); });
  it('throttles repeated failed sign-ins', async () => { for (let i = 0; i < 3; i++) await c.j('POST', '/api/auth/login', { email: 'brute@example.com', password: 'x' }); const r = await c.j('POST', '/api/auth/login', { email: 'brute@example.com', password: 'x' }); assert.equal(r.status, 429); });
  it('protected routes need a valid, unexpired, correctly signed token', async () => {
    const { token, user } = await (async () => { const r = await c.j('POST', '/api/auth/login', { email: 'u1@example.com', password: 'password123' }); return r.body; })();
    assert.equal((await c.j('GET', '/api/auth/me')).status, 401); assert.equal((await c.j('GET', '/api/cases', undefined, 'garbage')).status, 401);
    const tampered = token.slice(0, -3) + (token.endsWith('AAA') ? 'BBB' : 'AAA'); assert.equal((await c.j('GET', '/api/auth/me', undefined, tampered)).status, 401);
    const secret = fs.readFileSync(path.join(app.cfg.dataDir, '.secret'), 'utf8').trim(); const now = Math.floor(Date.now() / 1000);
    assert.equal((await c.j('GET', '/api/auth/me', undefined, signJwt({ sub: user.id, iat: now - 100, exp: now - 10, jti: 'x', scp: 'access' }, secret))).status, 401, 'expired');
    assert.equal((await c.j('GET', '/api/auth/me', undefined, signJwt({ sub: user.id, iat: now, exp: now + 100, jti: 'y', scp: 'mcp' }, secret))).status, 401, 'MCP-scoped tokens are refused on the REST API');
    assert.equal((await c.j('GET', '/api/auth/me', undefined, signJwt({ sub: user.id, iat: now, exp: now + 100, jti: 'z', scp: 'access' }, 'wrong-secret-wrong-secret'))).status, 401);
    const me = await c.j('GET', '/api/auth/me', undefined, token); assert.equal(me.status, 200); assert.equal(me.body.user.email, 'u1@example.com'); });
  it('logout revokes the token', async () => { const { token } = (await c.j('POST', '/api/auth/login', { email: 'u1@example.com', password: 'password123' })).body; assert.equal((await c.j('POST', '/api/auth/logout', {}, token)).status, 200); assert.equal((await c.j('GET', '/api/auth/me', undefined, token)).status, 401); });
});

describe('cases, uploads, storage', () => {
  let app, c, A, B; before(async () => { app = mk({ maxUploadBytes: 60000 }); c = await client(app); A = await signup(c, 1); B = await signup(c, 2); }); after(() => app.close());
  it('case CRUD with validation and unique ids', async () => {
    assert.equal((await c.j('POST', '/api/cases', { name: '  ' }, A.token)).status, 422); const x = await c.j('POST', '/api/cases', { name: 'Commercial dispute', type: 'Civil', jurisdiction: 'Mumbai', description: 'd' }, A.token), y = await c.j('POST', '/api/cases', { name: 'Property matter' }, A.token);
    assert.match(x.body.case.id, /^NS-\d{4}-\d{3}$/); assert.notEqual(x.body.case.id, y.body.case.id); const id = x.body.case.id;
    assert.equal((await c.j('PUT', `/api/cases/${id}`, { name: 'Renamed', court: 'High Court' }, A.token)).body.case.name, 'Renamed'); assert.equal((await c.j('GET', '/api/cases', undefined, A.token)).body.cases.length, 2);
    assert.equal((await c.j('POST', `/api/cases/${id}/archive`, { archived: true }, A.token)).body.case.status, 'ARCHIVED'); assert.equal((await c.j('POST', `/api/cases/${id}/documents`, { filename: 'a.txt', contentBase64: Buffer.from('some text content here for the case').toString('base64') }, A.token)).status, 409, 'archived cases are read-only');
    assert.equal((await c.j('DELETE', `/api/cases/${y.body.case.id}`, undefined, A.token)).status, 200); assert.equal((await c.j('GET', `/api/cases/${y.body.case.id}`, undefined, A.token)).status, 404); });
  it('user isolation: user B can never see or touch user A\'s case (all surfaces)', async () => {
    const cid = await seedCase(c, A.token, 'Private'); await seedAuthorities(c, A.token);
    for (const [m, p, body] of [['GET', `/api/cases/${cid}`], ['GET', `/api/cases/${cid}/snapshot`], ['PUT', `/api/cases/${cid}`, { name: 'x' }], ['DELETE', `/api/cases/${cid}`], ['POST', `/api/cases/${cid}/analyze`, {}], ['GET', `/api/cases/${cid}/claims`], ['GET', `/api/cases/${cid}/documents`], ['GET', `/api/cases/${cid}/documents/DOC-001/file`], ['POST', `/api/cases/${cid}/documents`, { filename: 'a.txt', contentBase64: 'aGVsbG8=' }], ['GET', `/api/cases/${cid}/audit`], ['GET', `/api/cases/${cid}/report`], ['POST', `/api/cases/${cid}/report`, {}], ['GET', `/api/cases/${cid}/reports/RPT-001/pdf`], ['POST', `/api/cases/${cid}/findings/F-001/review`, { action: 'accept' }], ['GET', `/api/claims/C-01?case_id=${cid}`]]) {
      const r = await c.j(m, p, body, B.token); assert.equal(r.status, 404, `${m} ${p} -> ${r.status}`); assert.equal(r.body.error.code, 'CASE_NOT_FOUND'); }
    assert.deepEqual((await c.j('GET', '/api/cases', undefined, B.token)).body.cases, []); assert.deepEqual((await c.j('GET', '/api/authorities', undefined, B.token)).body.authorities, []); assert.equal((await c.j('GET', '/api/sync', undefined, B.token)).body.cases.length, 0);
    const mcp = await c.j('POST', '/api/mcp/call', { tool: 'get_claims', args: { case_id: cid } }, B.token); assert.ok(mcp.body.error && /CASE_NOT_FOUND|PERMISSION_DENIED/.test(mcp.body.error.code)); assert.equal((await c.j('GET', '/api/cases/' + cid, undefined, A.token)).status, 200); });
  it('stores the original file and extracted text under uploads/{user}/{case}/…, with a checksum', async () => {
    const cid = (await c.j('POST', '/api/cases', { name: 'Files' }, A.token)).body.case.id; const r = await c.j('POST', `/api/cases/${cid}/documents`, { filename: 'Witness Statement.txt', contentBase64: b64(path.join(DATA, 'PW-3 Statement.txt')) }, A.token); assert.equal(r.status, 201); const d = r.body.document;
    const abs = path.join(app.cfg.uploadsDir, d.storagePath); assert.ok(fs.existsSync(abs)); assert.ok(d.storagePath.startsWith(`${A.user.id}/${cid}/documents/`)); assert.equal(fs.readFileSync(abs, 'utf8'), fs.readFileSync(path.join(DATA, 'PW-3 Statement.txt'), 'utf8')); assert.ok(fs.existsSync(path.join(app.cfg.uploadsDir, A.user.id, cid, 'extracted', d.id + '.txt'))); assert.match(d.sha256, /^[a-f0-9]{64}$/);
    const dl = await c.j('GET', `/api/cases/${cid}/documents/${d.id}/file`, undefined, A.token); assert.equal(dl.status, 200); assert.equal(dl.body.toString(), fs.readFileSync(path.join(DATA, 'PW-3 Statement.txt'), 'utf8')); assert.match(dl.headers.get('content-disposition'), /attachment/);
    const tr = await c.j('POST', `/api/cases/${cid}/transcripts`, { text: '10:06:18 PW-3: I saw the person near the gate at about 9:30 PM.\n10:07:02 Counsel: Are you sure?', hearingDate: '2026-03-20', hearingNumber: '3' }, A.token); assert.equal(tr.status, 201); assert.equal(tr.body.document.kind, 'transcript'); assert.ok(tr.body.document.storagePath.includes('/transcripts/')); assert.equal(tr.body.document.statementCount, 2);
    const db = new DatabaseSync(app.cfg.dbFile); assert.equal(db.prepare('SELECT COUNT(*) n FROM documents WHERE case_id=?').get(cid).n, 1); assert.equal(db.prepare('SELECT COUNT(*) n FROM transcripts WHERE case_id=?').get(cid).n, 1); db.close(); });
  it('blocks path traversal and unsafe names; the stored path never leaves the upload root', async () => {
    const cid = (await c.j('POST', '/api/cases', { name: 'Traversal' }, A.token)).body.case.id; const body = Buffer.from('A harmless statement that is long enough to parse properly.').toString('base64');
    for (const name of ['../../../etc/passwd.txt', '..\\..\\win.txt', 'a/b/c.txt', '.hidden.txt', 'x\u0000y.txt']) { const r = await c.j('POST', `/api/cases/${cid}/documents`, { filename: name, contentBase64: body }, A.token); assert.equal(r.status, 201, name); const p = path.resolve(app.cfg.uploadsDir, r.body.document.storagePath); assert.ok(p.startsWith(path.resolve(app.cfg.uploadsDir) + path.sep), 'inside root: ' + p); assert.equal(path.dirname(p), path.resolve(app.cfg.uploadsDir, A.user.id, cid, 'documents'), 'file sits directly in the documents folder: ' + r.body.document.storagePath); }
    assert.equal((await c.j('GET', `/api/cases/..%2F..%2Fetc/documents`, undefined, A.token)).status, 404); });
  it('rejects unsupported types, mismatched content, empty, oversize and malformed uploads', async () => {
    const cid = (await c.j('POST', '/api/cases', { name: 'Bad uploads' }, A.token)).body.case.id; const up = (o) => c.j('POST', `/api/cases/${cid}/documents`, o, A.token);
    assert.equal((await up({ filename: 'x.exe', contentBase64: 'TVo=' })).status, 415); assert.equal((await up({ filename: 'fake.pdf', contentBase64: Buffer.from('not a pdf at all').toString('base64') })).status, 415); assert.equal((await up({ filename: 'fake.docx', contentBase64: Buffer.from('not a zip at all').toString('base64') })).status, 415);
    assert.equal((await up({ filename: 'bin.txt', contentBase64: Buffer.from([65, 0, 66, 0, 67]).toString('base64') })).status, 415); assert.equal((await up({ filename: 'e.txt', contentBase64: '' })).status, 422); assert.equal((await up({ filename: 'big.txt', contentBase64: Buffer.alloc(70000, 65).toString('base64') })).status, 413);
    assert.equal((await up({ filename: 'nb.txt', contentBase64: '***not base64***' })).status, 413); assert.equal((await up({ filename: '', contentBase64: 'aGk=' })).status, 422); assert.equal((await up({})).status, 422); });
  it('parses real DOCX and PDF uploads server-side', async () => {
    const cid = (await c.j('POST', '/api/cases', { name: 'Formats' }, A.token)).body.case.id; const d = await c.j('POST', `/api/cases/${cid}/documents`, { filename: 'a.docx', contentBase64: b64(path.join(FIX, 'fixture.docx')) }, A.token); const p = await c.j('POST', `/api/cases/${cid}/documents`, { filename: 'a.pdf', contentBase64: b64(path.join(FIX, 'fixture.pdf')) }, A.token);
    assert.equal(d.status, 201, JSON.stringify(d.body)); assert.equal(p.status, 201, JSON.stringify(p.body)); assert.equal(d.body.document.pageCount, 2); assert.equal(p.body.document.pageCount, 2); const snap = p.body.snapshot; assert.ok(snap.documents.some(x => x.pages.some(pg => pg.paras.some(pp => /Location E/.test(pp.text))))); });
});

describe('analysis, review, audit, reports, persistence', () => {
  const dir = newDir(); let app, c, A, cid;
  before(async () => { app = mk({ dataDir: dir }); c = await client(app); A = await signup(c, 1); await seedAuthorities(c, A.token); cid = await seedCase(c, A.token); });
  after(() => app.close());
  it('analysis runs in the background with real agent run records', async () => {
    const st = await c.j('POST', `/api/cases/${cid}/analyze`, {}, A.token); assert.equal(st.status, 202); assert.match(st.body.run_id, /^AN-/); 
    const done = await waitDone(c, cid, A.token); assert.equal(done.analysis.status, 'completed'); assert.equal(done.agent_runs.length, 8); assert.deepEqual(done.agent_runs.map(r => r.agent), ['document_agent', 'transcript_agent', 'claim_agent', 'evidence_agent', 'conflict_agent', 'legal_research_agent', 'citation_audit_agent', 'report_agent']);
    const dbt = new DatabaseSync(app.cfg.dbFile); const tools = new Set(dbt.prepare('SELECT DISTINCT tool FROM tool_calls WHERE case_id=?').all(cid).map(r => r.tool)); dbt.close(); for (const t of ['get_case_material', 'get_claims', 'get_evidence', 'search_authorities', 'get_authority_excerpt', 'find_claim_conflicts', 'get_audit_history']) assert.ok(tools.has(t), 'tool used: ' + t);
    const claims = (await c.j('GET', `/api/cases/${cid}/claims`, undefined, A.token)).body.claims; assert.ok(claims.length >= 15); assert.ok(claims.every(x => x.sourceDocId && x.page && x.para && x.status)); assert.ok((await c.j('GET', `/api/cases/${cid}/conflicts`, undefined, A.token)).body.conflicts.length >= 1);
    assert.ok(!/(is lying|guilty|perjur)/i.test(JSON.stringify((await c.j('GET', `/api/cases/${cid}/conflicts`, undefined, A.token)).body))); });
  it('rows are written to the relational tables', () => { const db = new DatabaseSync(app.cfg.dbFile); const n = t => db.prepare(`SELECT COUNT(*) n FROM ${t} WHERE case_id=?`).get(cid).n; assert.ok(n('claims') >= 15); assert.ok(n('evidence') >= 8); assert.ok(n('claim_evidence') >= 8); assert.ok(n('conflicts') >= 1); assert.equal(n('agent_runs'), 8); assert.ok(n('audit_events') > 20); assert.ok(n('tool_calls') > 10); assert.ok(n('citations') >= 3); assert.ok(n('findings') >= 10);
    const cl = db.prepare('SELECT * FROM claims WHERE case_id=? LIMIT 1').get(cid); assert.ok(cl.claim_text && cl.source_document_id && cl.page > 0 && cl.line_end > cl.line_start); assert.ok(db.prepare('SELECT COUNT(*) n FROM authorities').get().n === 8); db.close(); });
  it('claim detail exposes evidence, conflicts, authorities and traceable source location', async () => {
    const cl = (await c.j('GET', `/api/cases/${cid}/claims`, undefined, A.token)).body.claims.find(x => /Location A at approximately 9:30/.test(x.text)); const r = await c.j('GET', `/api/cases/${cid}/claims/${cl.id}`, undefined, A.token); assert.equal(r.status, 200); assert.ok(r.body.evidence.length >= 3); assert.ok(r.body.conflicts.length >= 1); assert.ok(r.body.evidence.every(e => e.rel.reason && e.rel.sourceLocation));
    const alias = await c.j('GET', `/api/claims/${cl.id}?case_id=${cid}`, undefined, A.token); assert.equal(alias.body.claim.id, cl.id); assert.equal((await c.j('GET', `/api/cases/${cid}/claims/C-999`, undefined, A.token)).status, 404); assert.equal((await c.j('GET', `/api/claims/${cl.id}`, undefined, A.token)).status, 422); });
  it('human review: validates, records, audits, and never overwrites the AI finding', async () => {
    const snap = (await c.j('GET', `/api/cases/${cid}/snapshot`, undefined, A.token)).body.snapshot; const f = snap.findings.find(x => x.kind === 'CONFLICT'); const before = JSON.stringify(f);
    assert.equal((await c.j('POST', `/api/cases/${cid}/findings/${f.id}/review`, {}, A.token)).status, 422); assert.equal((await c.j('POST', `/api/cases/${cid}/findings/${f.id}/review`, { action: 'comment' }, A.token)).status, 422); assert.equal((await c.j('POST', `/api/cases/${cid}/findings/F-999/review`, { action: 'accept' }, A.token)).status, 404);
    await c.j('POST', `/api/cases/${cid}/findings/${f.id}/open`, {}, A.token); const r = await c.j('POST', `/api/cases/${cid}/findings/${f.id}/review`, { action: 'verify', comment: 'Verify device ownership and location accuracy.' }, A.token); assert.equal(r.status, 201); assert.equal(r.body.review.newStatus, 'NEEDS_VERIFICATION'); assert.equal(r.body.review.previousStatus, 'PENDING');
    const after = r.body.snapshot.findings.find(x => x.id === f.id); assert.equal(JSON.stringify(after), before, 'AI finding unchanged'); const ev = (await c.j('GET', `/api/cases/${cid}/audit`, undefined, A.token)).body.events.map(e => e.event); for (const e of ['REVIEWER_OPENED_FINDING', 'REVIEWER_CHANGED_STATUS', 'REVIEWER_ADDED_COMMENT', 'REVIEW_SAVED']) assert.ok(ev.includes(e), e);
    const claimId = snap.claims[3].id; const viaClaim = await c.j('POST', `/api/claims/${claimId}/review`, { case_id: cid, action: 'modify', modifiedText: 'Reviewer wording' }, A.token); assert.equal(viaClaim.status, 201); assert.equal(viaClaim.body.snapshot.claims.find(x => x.id === claimId).text, snap.claims[3].text, 'original claim text kept');
    assert.equal((await c.j('GET', `/api/cases/${cid}/reviews`, undefined, A.token)).body.reviews.length, 2); const db = new DatabaseSync(app.cfg.dbFile); assert.equal(db.prepare('SELECT COUNT(*) n FROM reviews WHERE case_id=?').get(cid).n, 2); db.close(); });
  it('reports: JSON, PDF (stored + downloadable), disclaimer, no secrets', async () => {
    const pre = await c.j('GET', `/api/cases/${cid}/report`, undefined, A.token); assert.match(pre.body.report.disclaimer, /does not determine guilt/); const r = await c.j('POST', `/api/cases/${cid}/report`, {}, A.token); assert.equal(r.status, 201); assert.equal(r.body.report_id, 'RPT-001');
    assert.ok(fs.existsSync(path.join(app.cfg.uploadsDir, A.user.id, cid, 'reports', 'RPT-001.pdf'))); assert.ok(fs.existsSync(path.join(app.cfg.uploadsDir, A.user.id, cid, 'reports', 'RPT-001.json'))); const pdf = await c.j('GET', r.body.pdf_url, undefined, A.token); assert.equal(pdf.status, 200); assert.equal(pdf.body.subarray(0, 5).toString(), '%PDF-'); assert.equal(pdf.headers.get('content-type'), 'application/pdf');
    assert.ok(!JSON.stringify(r.body.report).match(/passwordHash|pbkdf2|token/i)); assert.equal((await c.j('GET', `/api/cases/${cid}/reports/RPT-999/pdf`, undefined, A.token)).status, 404); assert.equal((await c.j('GET', `/api/cases/${cid}/reports/..%2F..%2Fx/pdf`, undefined, A.token)).status, 404); });
  it('everything survives a server restart and the old token still works', async () => {
    const token = A.token; const before = (await c.j('GET', `/api/cases/${cid}/snapshot`, undefined, token)).body.snapshot; await app.close();
    app = mk({ dataDir: dir, paceMs: 400 }); c = await client(app); const me = await c.j('GET', '/api/auth/me', undefined, token); assert.equal(me.status, 200, 'token survives restart');
    const after = (await c.j('GET', `/api/cases/${cid}/snapshot`, undefined, token)).body.snapshot; for (const k of ['documents', 'claims', 'evidence', 'relationships', 'conflicts', 'citations', 'findings', 'reviews', 'audit', 'agentRuns', 'reports', 'authorityLinks']) assert.equal(after[k].length, before[k].length, k); assert.deepEqual(after.claims.map(x => x.id), before.claims.map(x => x.id)); assert.equal(after.documents[0].pages[0].paras[0].text, before.documents[0].pages[0].paras[0].text);
    assert.equal((await c.j('GET', '/api/authorities', undefined, token)).body.authorities.length, 8); const login = await c.j('POST', '/api/auth/login', { email: 'u1@example.com', password: 'password123' }); assert.equal(login.status, 200);
  });
  it('a hard crash mid-analysis (SIGKILL of a real server process) leaves data intact and the run marked interrupted', async () => {
    const d = newDir(); const start = () => new Promise((res, rej) => { const p = spawn(process.execPath, ['--disable-warning=ExperimentalWarning', path.join(__dirname, '..', 'src', 'server.js')], { env: { ...process.env, DATA_DIR: d, PORT: '0', HOST: '127.0.0.1', ANALYSIS_PACE_MS: '600', LOG_LEVEL: 'info' }, stdio: ['ignore', 'pipe', 'inherit'] }); let buf = ''; p.stdout.on('data', x => { buf += x; const m = buf.match(/"url":"(http:[^"]+)"/); if (m) res({ p, base: m[1] }); }); p.on('error', rej); setTimeout(() => rej(new Error('server did not start')), 8000); });
    const call = async (base, m, pth, body, token) => { const r = await fetch(base + pth, { method: m, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: 'Bearer ' + token } : {}) }, body: body ? JSON.stringify(body) : undefined }); return { status: r.status, body: await r.json() }; };
    let s = await start(); const su = await call(s.base, 'POST', '/api/auth/signup', SIGN(9)); const token = su.body.token; const cs = await call(s.base, 'POST', '/api/cases', { name: 'Crash test' }, token); const id = cs.body.case.id;
    for (const f of ['PW-3 Statement.txt', 'CCTV Review Report.txt', 'Device Location Record.txt']) await call(s.base, 'POST', `/api/cases/${id}/documents`, { filename: f, contentBase64: b64(path.join(DATA, f)) }, token);
    const st = await call(s.base, 'POST', `/api/cases/${id}/analyze`, {}, token); assert.equal(st.status, 202); await new Promise(r => setTimeout(r, 900)); const mid = await call(s.base, 'GET', `/api/cases/${id}/analysis`, null, token); assert.equal(mid.body.analysis.status, 'running'); const dup = await call(s.base, 'POST', `/api/cases/${id}/analyze`, {}, token); assert.equal(dup.status, 409);
    s.p.kill('SIGKILL'); await new Promise(r => s.p.on('exit', r));
    s = await start(); try { const snap = (await call(s.base, 'GET', `/api/cases/${id}/snapshot`, null, token)); assert.equal(snap.status, 200, 'token still valid after crash'); const C = snap.body.snapshot; assert.equal(C.documents.length, 3); assert.equal(C.analysis.status, 'failed'); assert.notEqual(C.status, 'ANALYZING'); assert.ok(C.audit.some(e => e.event === 'ANALYSIS_INTERRUPTED')); assert.ok(C.analysis.stages.every(x => x.status !== 'running'));
      const ok = await call(s.base, 'POST', `/api/cases/${id}/analyze`, {}, token); assert.equal(ok.status, 202, 'can re-run after the crash'); } finally { s.p.kill('SIGKILL'); } });
  it('deleting a case removes its rows and stored files', async () => { const token = A.token; const tmp = (await c.j('POST', '/api/cases', { name: 'Temp' }, token)).body.case.id; await c.j('POST', `/api/cases/${tmp}/documents`, { filename: 'a.txt', contentBase64: Buffer.from('Some statement text long enough to be accepted here.').toString('base64') }, token); const dirp = path.join(app.cfg.uploadsDir, A.user.id, tmp); assert.ok(fs.existsSync(dirp)); await c.j('DELETE', `/api/cases/${tmp}`, undefined, token); assert.ok(!fs.existsSync(dirp)); const db = new DatabaseSync(app.cfg.dbFile); assert.equal(db.prepare('SELECT COUNT(*) n FROM documents WHERE case_id=?').get(tmp).n, 0); db.close(); });
});

describe('reading and writing while an analysis is still running', () => {
  it('snapshots and status can be read mid-run (pending values persist safely) and the final state is consistent in SQLite', async () => {
    const app = mk({ paceMs: 120 }); const c = await client(app); try { const A = await signup(c, 1); const cid = await seedCase(c, A.token); assert.equal((await c.j('POST', `/api/cases/${cid}/analyze`, {}, A.token)).status, 202); let sawRunning = 0;
      for (let i = 0; i < 100; i++) { const s = await c.j('GET', `/api/cases/${cid}/snapshot`, undefined, A.token); assert.equal(s.status, 200, JSON.stringify(s.body)); const st = s.body.snapshot.analysis.status; if (st === 'running') { sawRunning++; assert.equal((await c.j('GET', '/api/cases', undefined, A.token)).status, 200); } else break; await new Promise(r => setTimeout(r, 60)); }
      assert.ok(sawRunning >= 2, 'observed the run in progress'); const done = await waitDone(c, cid, A.token); assert.equal(done.analysis.status, 'completed'); const db = new DatabaseSync(app.cfg.dbFile); assert.equal(db.prepare('SELECT COUNT(*) n FROM claims WHERE support_strength IS NULL AND case_id=?').get(cid).n, 0, 'final rows carry signals'); db.close(); } finally { await app.close(); } });
});

describe('authority library API and MCP tools', () => {
  let app, c, A, B, cid; before(async () => { app = mk(); c = await client(app); A = await signup(c, 1); B = await signup(c, 2); await seedAuthorities(c, A.token); cid = await seedCase(c, A.token); await c.j('POST', `/api/cases/${cid}/analyze`, {}, A.token); await waitDone(c, cid, A.token); }); after(() => app.close());
  it('starts empty for every user, validates input, searches, isolates and removes', async () => {
    assert.deepEqual((await c.j('GET', '/api/authorities', undefined, B.token)).body.authorities, []); const bad = await c.j('POST', '/api/authorities', { title: 'x', text: 'short' }, B.token); assert.equal(bad.status, 422); assert.ok(bad.body.error.errors.title && bad.body.error.errors.text);
    const s = await c.j('GET', '/api/authorities/search?q=' + encodeURIComponent('phone metadata handset location cell tower'), undefined, A.token); assert.equal(s.body.results[0].citation, 'DEMO-002'); assert.ok(s.body.results.every(r => r.source === 'authority_library')); assert.deepEqual((await c.j('GET', '/api/authorities/search?q=handset+location', undefined, B.token)).body.results, []);
    assert.equal((await c.j('DELETE', '/api/authorities/AUTH-001', undefined, B.token)).status, 404); const add = await c.j('POST', '/api/authorities', { title: 'Sample Act, 2001', citation: 'Sample Act 2001', kind: 'Statute', text: '12. A person who signs a contract must be given a copy within seven days of signing.' }, B.token); assert.equal(add.status, 201); assert.equal((await c.j('DELETE', '/api/authorities/' + add.body.authority.id, undefined, B.token)).status, 200); });
  it('HTTP tool layer lists 7 tools and enforces ownership and validation', async () => {
    const t = await c.j('GET', '/api/mcp/tools', undefined, A.token); assert.equal(t.body.tools.length, 7); const ok = await c.j('POST', '/api/mcp/call', { tool: 'get_claims', args: { case_id: cid } }, A.token); assert.ok(ok.body.claims.length >= 15); assert.ok(ok.body.confidence_note);
    for (const args of [{ case_id: '../../x' }, {}, { case_id: 'NS-1999-001' }]) { const r = await c.j('POST', '/api/mcp/call', { tool: 'get_claims', args }, A.token); assert.ok(r.body.error && r.body.error.code && !JSON.stringify(r.body).includes(' at ')); }
    assert.equal((await c.j('POST', '/api/mcp/call', { tool: 'drop_tables', args: {} }, A.token)).body.error.code, 'TOOL_NOT_FOUND'); });
  it('MCP stdio server speaks JSON-RPC, lists 7 tools, runs them as the token owner and refuses everything else', async () => {
    const tok = (await c.j('POST', '/api/auth/mcp-token', {}, A.token)).body.token; const tokB = (await c.j('POST', '/api/auth/mcp-token', {}, B.token)).body.token;
    const spawnMcp = (token) => { const p = spawn(process.execPath, ['--disable-warning=ExperimentalWarning', path.join(__dirname, '..', 'mcp-server.js')], { env: { ...process.env, DATA_DIR: app.cfg.dataDir, DATABASE_FILE: app.cfg.dbFile, NS_MCP_TOKEN: token }, stdio: ['pipe', 'pipe', 'pipe'] }); const q = []; let buf = ''; p.stdout.on('data', d => { buf += d; let i; while ((i = buf.indexOf('\n')) >= 0) { const l = buf.slice(0, i); buf = buf.slice(i + 1); if (l.trim()) q.push(JSON.parse(l)); } }); let id = 0;
      const call = (method, params) => new Promise((res, rej) => { const my = ++id; p.stdin.write(JSON.stringify({ jsonrpc: '2.0', id: my, method, params }) + '\n'); const t0 = Date.now(); const iv = setInterval(() => { const k = q.findIndex(m => m.id === my); if (k >= 0) { clearInterval(iv); res(q.splice(k, 1)[0]); } else if (Date.now() - t0 > 8000) { clearInterval(iv); rej(new Error('mcp timeout')); } }, 10); }); return { p, call }; };
    const m = spawnMcp(tok); try {
      const init = await m.call('initialize', { protocolVersion: '2024-11-05', capabilities: {}, clientInfo: { name: 't', version: '1' } }); assert.equal(init.result.serverInfo.name, 'nyayasahayak'); assert.ok(init.result.capabilities.tools); m.p.stdin.write(JSON.stringify({ jsonrpc: '2.0', method: 'notifications/initialized' }) + '\n');
      const list = await m.call('tools/list', {}); assert.deepEqual(list.result.tools.map(x => x.name).sort(), ['find_claim_conflicts', 'get_audit_history', 'get_authority_excerpt', 'get_case_material', 'get_claims', 'get_evidence', 'search_authorities']); assert.ok(list.result.tools.every(x => x.inputSchema.type === 'object'));
      const claims = await m.call('tools/call', { name: 'get_claims', arguments: { case_id: cid } }); assert.equal(claims.result.isError, false); const body = JSON.parse(claims.result.content[0].text); assert.ok(body.claims.length >= 15);
      const conf = JSON.parse((await m.call('tools/call', { name: 'find_claim_conflicts', arguments: { case_id: cid, claim_id: body.claims[0].id } })).result.content[0].text); assert.ok(Array.isArray(conf.conflicts));
      const sa = JSON.parse((await m.call('tools/call', { name: 'search_authorities', arguments: { query: 'phone metadata handset location', limit: 2 } })).result.content[0].text); assert.ok(sa.results.length >= 1); const ex = JSON.parse((await m.call('tools/call', { name: 'get_authority_excerpt', arguments: { authority_id: sa.results[0].authority_id } })).result.content[0].text); assert.equal(ex.source, 'authority_library'); assert.ok(ex.excerpt.length > 20);
      const hist = JSON.parse((await m.call('tools/call', { name: 'get_audit_history', arguments: { case_id: cid } })).result.content[0].text); assert.ok(hist.events.length > 10);
      const unknown = await m.call('tools/call', { name: 'delete_everything', arguments: {} }); assert.ok(unknown.error); const bad = await m.call('tools/call', { name: 'get_claims', arguments: { case_id: "x'; DROP TABLE cases;--" } }); assert.equal(bad.result.isError, true); assert.equal(JSON.parse(bad.result.content[0].text).error.code, 'VALIDATION_ERROR'); assert.equal((await m.call('nope', {})).error.code, -32601);
    } finally { m.p.kill(); }
    const mb = spawnMcp(tokB); try { await mb.call('initialize', {}); const r = await mb.call('tools/call', { name: 'get_claims', arguments: { case_id: cid } }); assert.equal(r.result.isError, true); assert.match(JSON.parse(r.result.content[0].text).error.code, /CASE_NOT_FOUND|PERMISSION_DENIED/); const a = JSON.parse((await mb.call('tools/call', { name: 'search_authorities', arguments: { query: 'phone metadata handset' } })).result.content[0].text); assert.deepEqual(a.results, [], 'another user\'s library is invisible'); } finally { mb.p.kill(); }
    for (const token of ['', 'garbage', A.token]) { const code = await new Promise(res => { const p = spawn(process.execPath, ['--disable-warning=ExperimentalWarning', path.join(__dirname, '..', 'mcp-server.js')], { env: { ...process.env, DATA_DIR: app.cfg.dataDir, NS_MCP_TOKEN: token }, stdio: 'ignore' }); p.on('exit', res); }); assert.equal(code, 2, 'refuses to start without a valid MCP-scoped token: ' + (token ? token.slice(0, 6) : '(empty)')); } });
});

describe('server-side Gemini', () => {
  const KEY = 'SERVER-ONLY-KEY-987654'; let app, c, A, cid, real, calls;
  before(async () => { real = globalThis.fetch; calls = []; app = mk({ geminiKey: KEY, geminiModel: 'gemini-2.5-flash' }); c = await client(app); A = await signup(c, 1); cid = await seedCase(c, A.token);
    const mock = async (url, opts) => { if (String(url).startsWith('http://127.0.0.1')) return real(url, opts); calls.push({ url: String(url), key: opts.headers['x-goog-api-key'], prompt: JSON.parse(opts.body).contents[0].parts[0].text }); const prompt = JSON.parse(opts.body).contents[0].parts[0].text; const line = prompt.split('\n').find(l => /I saw Person A near Location A at approximately 9:30 PM/.test(l)); const id = ((line || prompt).match(/\[(P\d+\.\d+)\]/) || [])[1] || 'P1.2'; return { ok: true, status: 200, json: async () => ({ candidates: [{ content: { parts: [{ text: JSON.stringify({ claims: [{ paragraph_id: id, quote: 'I saw Person A near Location A at approximately 9:30 PM.', claim_type: 'LOCATION', speaker: 'PW-3', confidence: 0.9 }, { paragraph_id: id, quote: 'Person A confessed to the theft.', claim_type: 'FACTUAL', speaker: '', confidence: 0.99 }] }) }] } }] }) }; }; globalThis.fetch = mock; });
  after(async () => { globalThis.fetch = real; await app.close(); });
  it('the key never reaches the client; no consent means no network call', async () => {
    const st = await c.j('GET', '/api/ai/status', undefined, A.token); assert.equal(st.body.keyConfiguredOnServer, true); assert.equal(st.body.consent, false); assert.ok(!JSON.stringify(st.body).includes(KEY)); assert.ok(!JSON.stringify((await c.j('GET', '/api/health')).body).includes(KEY));
    await c.j('POST', `/api/cases/${cid}/analyze`, {}, A.token); const d = await waitDone(c, cid, A.token); assert.equal(calls.length, 0, 'no call without consent'); assert.equal(d.analysis.provider.name, 'local-rules'); });
  it('with consent: claims are quote-grounded, fabricated quotes are dropped, PII is masked before sending', async () => {
    assert.equal((await c.j('PUT', '/api/ai/settings', { consent: true, mask: true }, A.token)).status, 200); assert.equal((await c.j('PUT', '/api/ai/settings', { consent: true, model: '../bad model' }, A.token)).status, 422);
    await c.j('POST', `/api/cases/${cid}/analyze`, {}, A.token); const d = await waitDone(c, cid, A.token); assert.ok(calls.length >= 1); assert.equal(calls[0].key, KEY); assert.ok(!calls[0].url.includes(KEY)); assert.equal(d.analysis.provider.name, 'gemini+rules');
    const snap = (await c.j('GET', `/api/cases/${cid}/snapshot`, undefined, A.token)).body.snapshot; assert.ok(!snap.claims.some(x => /confessed/.test(x.text)), 'fabricated quote dropped'); const g = snap.claims.filter(x => x.provider === 'gemini'); assert.ok(g.length >= 1); g.forEach(x => { const para = snap.documents.find(y => y.id === x.sourceDocId).pages[x.page - 1].paras[x.para - 1].text; assert.equal(para.slice(x.start, x.end).toLowerCase(), x.text.toLowerCase()); });
    assert.ok(!JSON.stringify(snap).includes(KEY)); assert.ok(!JSON.stringify(d).includes(KEY)); assert.ok(!fs.readFileSync(app.cfg.dbFile).includes(KEY), 'key is not persisted in the database'); });
  it('a failing AI service degrades to the rules engine and says why, without the key', async () => {
    const prev = globalThis.fetch; globalThis.fetch = async (u, o) => String(u).startsWith('http://127.0.0.1') ? real(u, o) : { ok: false, status: 429, json: async () => ({}) };
    try { await c.j('POST', `/api/cases/${cid}/analyze`, {}, A.token); const d = await waitDone(c, cid, A.token); const run = d.agent_runs.find(r => r.agent === 'claim_agent'); assert.equal(run.status, 'degraded'); assert.ok(run.warnings.some(w => /rate limit/.test(w))); assert.ok(!JSON.stringify(d).includes(KEY)); } finally { globalThis.fetch = prev; } });
});
