const store={}; globalThis.localStorage={getItem:k=>k in store?store[k]:null,setItem:(k,v)=>{store[k]=String(v)},removeItem:k=>{delete store[k]}};
require('../dist/core.js'); const N=globalThis.NS;
(async()=>{
  const r=await N.signup({fullName:'Test User',email:'a@b.co',phone:'+91 9876543210',password:'password1',confirm:'password1',role:'LAWYER'});
  const u=r.user; const C=N.createDemoCase(u.id);
  console.log('case',C.id,C.documents.map(d=>d.id+':'+d.pageCount).join(' '));
  await N.runAnalysis(u.id,C.id,{paceMs:0});
  const c=N.ownedCase(u.id,C.id);
  console.log('claims',c.claims.length); c.claims.forEach(k=>console.log(k.id,k.type,k.sourceDocId,'p'+k.page+'¶'+k.para,'|',k.speaker,'|',k.eventTime&&k.eventTime.text,'|',k.locations.map(l=>l.label).join('/'),'|',k.anchors.join(','),'|',k.text.slice(0,70),'| sup',k.supportStrength,'con',k.conflictStrength,'unc',k.uncertainty));
  console.log('evidence',c.evidence.map(e=>e.id+':'+e.type+':'+e.sourceDocId).join(' '));
  console.log('rels',c.relationships.length, c.relationships.slice(0,40).map(r=>r.claimId+' '+r.relationship[0]+' '+r.evidenceId).join(', '));
  console.log('conflicts',c.conflicts.map(k=>k.id+' '+k.type+' '+k.claimA+'~'+k.claimB+' '+k.comparison).join('\n'));
  console.log(c.conflicts[0]&&c.conflicts[0].description);
  console.log('authLinks',c.authorityLinks.map(a=>a.claimId+'->'+a.authorityId+'#'+a.passageIndex+' '+a.score).join(', '));
  console.log('citations',c.citations.map(x=>x.id+' '+x.claimId+' '+x.citationText.slice(0,30)+' => '+x.result+' '+x.relevanceSignal).join('\n'));
  console.log('findings',c.findings.length, c.findings.map(f=>f.id+':'+f.kind).join(' '));
  console.log('runs',c.agentRuns.map(r=>r.agent+':'+r.status+':'+r.durationMs+'ms mcp'+r.mcpCalls+' | '+r.outputSummary).join('\n'));
  console.log('tools',c.toolCalls.length,[...new Set(c.toolCalls.map(t=>t.tool))]);
  console.log('status',c.status,N.caseMetrics(c));
})().catch(e=>{console.error('ERR',e);process.exit(1)});
