/* ===== 23 ui docs: repository, upload, source viewer, hearing workstation ===== */
UI.df = { q: '', f: 'All' }; UI.uq = []; UI.dv = null; UI.hv = { spk: null, max: 120 };
const qRe = q => new RegExp('(' + q.replace(/[.*+?^${}()|[\]\\]/g, '\\$&') + ')', 'gi');
const markQ = (t, q) => (q && q.length > 1) ? t.split(qRe(q)).map((p, i) => i % 2 ? `<mark class="q">${esc(p)}</mark>` : esc(p)).join('') : esc(t);
const docStatus = d => ({ Indexed: 'INDEXED', 'Needs Review': 'NEEDS_REVIEW' }[d.status] || 'INDEXED');
const KIND_OF_UNUSED = { Statements: ['Witness Statement', 'Affidavit', 'FIR / Complaint'], Reports: ['Investigation Report', 'Medical Report', 'Forensic Report', 'CCTV Report', 'Evidence Report', 'Charge Sheet'], Evidence: ['Phone / Digital Record', 'CCTV Report', 'Forensic Report', 'Medical Report'], Submissions: ['Court Filing', 'Written Submission'] };
const docHref = (C, d, extra = '') => d.kind === 'transcript' ? caseHref(C, 'hearing?doc=' + d.id + extra) : caseHref(C, 'documents/' + d.id + (extra ? '?' + extra.replace(/^&/, '') : ''));

function DocumentsView(C) {
  const ro = C.status === 'ARCHIVED'; const has = C.documents.length > 0;
  const F = ['All', 'Statements', 'Reports', 'Evidence', 'Submissions', 'Other'];
  const upload = ro ? '' : uploadPanel(C);
  return { title: 'Documents', crumbs: crumbsFor(C, ['Documents']), mount() { paintQueue(); paintDocs(); },
    html: `<div class="page"><div class="pagehead"><div><p class="lbl" style="margin-bottom:6px">Case documents</p><h1>Document library</h1><p class="sub" id="docsummary">The case repository. Text is extracted and indexed page by page so every claim can be traced back to its source.</p></div><div class="row wrap">${C.claims.length || !has ? '' : btn('Analyze materials', `data-act="run-analysis" data-case="${C.id}"`, { cls: 'primary', icon: 'play' })}${ro ? '' : btn('Add material', 'data-act="pick-files" data-target="docfile"', { cls: has && !C.claims.length ? '' : 'primary', icon: 'plus' })}</div></div>${upload}
    ${has ? `<div class="row wrap between" style="margin-bottom:14px"><div class="chips" id="docchips"></div><div class="searchin" style="width:280px;max-width:100%">${icon('search', 15)}<input type="text" data-in="docsq" placeholder="Search documents…" aria-label="Search documents" value="${esc(UI.df.q)}"></div></div><div id="doclist"></div>` : empty({ icon: 'folder', title: 'No case material', text: 'Upload documents to begin source-traceable analysis.', action: ro ? '' : `<div style="margin-top:10px">${btn('Add material', 'data-act="pick-files" data-target="docfile"', { cls: 'primary', icon: 'upload' })}</div>` })}</div>` };
}
function uploadPanel(C) {
  return `<section class="panel" id="uploadpanel" style="margin-bottom:18px"><div class="pb"><div class="drop" data-drop="docdrop" data-case="${C.id}">${icon('upload', 26)}<div class="serif" style="font-weight:600;font-size:17px">Drop case documents here</div><div class="muted">or</div>${btn('Browse files', `data-act="pick-files" data-target="docfile"`, { cls: 'primary' })}<div class="mono faint" style="font-size:12px">PDF · DOCX · TXT · up to 8 MB each</div><input id="docfile" type="file" multiple accept=".pdf,.docx,.txt,.md" class="hide" data-change="docfile" data-case="${C.id}"></div><div id="uploadq" class="col" style="gap:8px;margin-top:${UI.uq.length ? 14 : 0}px"></div><p class="faint" style="font-size:12.5px;margin-top:12px">Scanned or image-only PDFs need OCR, which is not available in this build. Add a hearing transcript on the <a href="${caseHref(C, 'hearing')}">Hearings page</a>.</p></div></section>`;
}
const DOC_FILTERS = { All: null, Pleadings: ['Court Filing', 'Written Submission'], FIR: ['FIR / Complaint', 'Charge Sheet'], 'Witness statements': ['Witness Statement', 'Affidavit'], Evidence: ['Phone / Digital Record', 'CCTV Report', 'Forensic Report', 'Medical Report', 'Evidence Report'], Reports: ['Investigation Report'], Transcripts: 'T', Other: 'O' };
const docMatch = (d, f) => { const v = DOC_FILTERS[f]; if (!v) return true; if (v === 'T') return d.kind === 'transcript'; if (v === 'O') return d.kind !== 'transcript' && !Object.values(DOC_FILTERS).some(a => Array.isArray(a) && a.includes(d.category)); return d.kind !== 'transcript' && v.includes(d.category); };
const srcType = d => d.kind === 'transcript' ? 'Hearing' : ({ txt: 'TXT', docx: 'DOCX', 'pdf-basic': 'PDF' }[d.extractor] || 'File');
function paintDocs() {
  const C = currentCaseSafe(); const el = $('#doclist'); if (!C || !el) return; const q = UI.df.q.trim().toLowerCase();
  const chips = $('#docchips'); if (chips) chips.innerHTML = Object.keys(DOC_FILTERS).map(f => `<button class="chip" aria-pressed="${UI.df.f === f}" data-act="doc-filter" data-k="${f}">${f}<span class="n">${C.documents.filter(d => docMatch(d, f)).length}</span></button>`).join('');
  const sum = $('#docsummary'); if (sum) { const ok = C.documents.filter(d => d.status === 'Indexed').length, rv = C.documents.filter(d => d.status === 'Needs Review').length; sum.textContent = `${plural(C.documents.length, 'document')} · ${ok} processed · ${rv} require review`; }
  const rows = C.documents.filter(d => docMatch(d, UI.df.f)).filter(d => !q || (d.filename + ' ' + d.category).toLowerCase().includes(q)); const ro = C.status === 'ARCHIVED';
  el.innerHTML = rows.length ? `<div class="tblwrap"><table><thead><tr><th>Document</th><th>Type</th><th>Source</th><th>Pages</th><th>Claims</th><th>Status</th><th>Uploaded</th><th><span class="sr">Actions</span></th></tr></thead><tbody>${rows.map(d => { const n = C.claims.filter(c => c.sourceDocId === d.id).length; return `<tr data-href="${docHref(C, d)}"><td><div class="row"><span class="ic-wrap" style="width:28px;height:28px;border-radius:4px;display:grid;place-items:center;background:var(--sunken);color:var(--text-2)">${icon(d.kind === 'transcript' ? 'mic' : 'file', 15)}</span><div style="min-width:0"><a href="${docHref(C, d)}" class="serif" style="color:var(--text);font-weight:600;font-size:14.5px">${esc(docName(d))}</a><div class="idcell faint">${d.id}${d.kind === 'transcript' && d.hearingDate ? ' · Hearing ' + esc(d.hearingNumber || '') + ' · ' + esc(d.hearingDate) : ''}</div></div></div></td><td>${ro || d.kind === 'transcript' ? esc(d.category) : `<select data-change="doccat" data-case="${C.id}" data-id="${d.id}" aria-label="Category for ${esc(d.filename)}" style="height:28px;width:auto;font-size:12.5px">${CATEGORIES.map(c => `<option ${c === d.category ? 'selected' : ''}>${c}</option>`).join('')}</select>`}</td><td class="mono">${srcType(d)}</td><td class="mono">${d.pageCount}</td><td class="mono">${n || '—'}</td><td>${badge(docStatus(d), d.status === 'Needs Review' ? 'Needs review' : 'Processed')}${d.extractNote ? `<div class="faint" style="font-size:12px;max-width:260px;margin-top:3px">${esc(d.extractNote)}</div>` : ''}</td><td class="muted">${esc(fmtDate(d.uploadedAt))}</td><td class="row" style="gap:2px"><a class="btn sm ghost" href="${docHref(C, d)}">Open</a>${Api.on ? `<button class="iconbtn" data-act="doc-download" data-id="${d.id}" aria-label="Download original ${esc(d.filename)}" title="Download the original file">${icon('download', 15)}</button>` : ''}${ro ? '' : `<button class="iconbtn" data-act="doc-remove" data-id="${d.id}" aria-label="Remove ${esc(d.filename)}">${icon('trash', 15)}</button>`}</td></tr>`; }).join('')}</tbody></table></div>` : empty({ icon: 'search', title: 'No documents match', text: 'Try another filter or search term.' });
}
ACT['doc-filter'] = el => { UI.df.f = el.dataset.k; paintDocs(); };
INPUT.docsq = t => { UI.df.q = t.value; paintDocs(); };
INPUT.doccat = async t => { try { await Data.setCategory(t.dataset.case, t.dataset.id, t.value); toast('Category updated. Re-run analysis to apply it.'); } catch (e) { toast('Unable to update the category.', 'bad'); } };
ACT['pick-files'] = el => { const i = $('#' + el.dataset.target); i && i.click(); };
ACT['doc-remove'] = el => { const C = currentCaseSafe(); const d = C.documents.find(x => x.id === el.dataset.id); confirmDialog({ title: 'Remove this document?', text: `“${esc(d.filename)}” will be removed from the case. Existing claims from it stay until you re-run analysis.`, label: 'Remove', danger: true, onConfirm: async () => { try { await Data.removeDocument(C.id, d.id); toast('Document removed.'); render(); } catch (e) { toast(e.message, 'bad'); } } }); };
ACT['doc-download'] = async el => { const C = currentCaseSafe(); const d = C && C.documents.find(x => x.id === el.dataset.id); if (!d) return; try { saveFile(d.filename, await Data.downloadOriginal(C.id, d), 'application/octet-stream'); } catch (e) { toast(e.message, 'bad'); } };

/* upload queue with truthful per-file states */
const stepHtml = (s, l) => `<span class="${s === 'done' ? 'done' : s === 'now' ? 'now' : s === 'err' ? 'err' : ''}">${icon(s === 'done' ? 'check' : s === 'now' ? 'refresh' : s === 'err' ? 'x' : 'circle', 12, s === 'now' ? 'spin' : '')}${l}</span>`;
function paintQueue() {
  const el = $('#uploadq'); if (!el) return;
  el.innerHTML = UI.uq.map(it => `<div class="upl"><div style="min-width:0"><div class="trunc" style="font-weight:580">${esc(it.name)}</div><div class="steps">${stepHtml(it.s.up, 'Uploaded')}${stepHtml(it.s.ext, 'Text extracted')}${stepHtml(it.s.idx, 'Indexed')}<span>${icon('circle', 12)}AI analysis</span></div>${it.err ? `<div style="color:var(--bad-t);font-size:12.5px;margin-top:4px">${esc(it.err)}</div>` : it.note ? `<div style="color:var(--warn-t);font-size:12.5px;margin-top:4px">${esc(it.note)}</div>` : ''}</div><div>${it.err ? badge('ERROR') : it.s.idx === 'done' ? badge('INDEXED') : badge('PROCESSING')}</div></div>`).join('');
}
async function ingest(caseId, files, opts = {}) {
  const u = UI.user; const list = Array.from(files); if (!list.length) return; const batch = list.map(f => ({ name: f.name, f, s: { up: 'now', ext: 'wait', idx: 'wait' }, err: null, note: '' }));
  UI.uq = batch.concat(UI.uq).slice(0, 12); paintQueue(); let ok = 0;
  for (const it of batch) {
    if (Api.on) {
      try { const d = await Data.uploadFile(caseId, it.f, opts); it.s.up = 'done'; it.s.ext = 'done'; it.s.idx = 'done'; it.note = d.extractNote || ''; ok++; } catch (e) { it.s.up = 'err'; it.err = e.message || 'The file could not be uploaded.'; }
      paintQueue(); continue;
    }
    const r = await parseFile(it.f);
    if (!r.ok) { it.s.up = 'err'; it.err = r.error; paintQueue(); continue; }
    it.s.up = 'done'; it.s.ext = 'done'; it.note = r.note || ''; it.s.idx = 'now'; paintQueue(); await sleep(140);
    try { DocSvc.add(u.id, caseId, { filename: it.name, text: r.text, mime: r.mime, size: it.f.size, extractor: r.extractor, extractNote: r.note || '', kind: opts.kind, hearingId: opts.hearingId, hearingDate: opts.hearingDate, hearingNumber: opts.hearingNumber }); it.s.idx = 'done'; ok++; }
    catch (e) { it.s.idx = 'err'; it.err = e.message || 'The file could not be indexed.'; }
    paintQueue();
  }
  if (ok) { toast(ok === 1 ? 'Document uploaded successfully.' : `${ok} documents uploaded successfully.`); const y = UI.uq; render(); UI.uq = y; paintQueue(); }
  else toast('No files were added. Check the messages below.', 'warn');
}
INPUT.docfile = t => { ingest(t.dataset.case, t.files); t.value = ''; };
INPUT.docdrop = (t) => ingest(t.dataset.case, t.files);

/* ---------- document viewer ---------- */
function paraHtml(text, cls, focusId, query, cites = []) {
  const pts = new Set([0, text.length]); cls.forEach(c => { pts.add(clamp(c.start, 0, text.length)); pts.add(clamp(c.end, 0, text.length)); }); cites.forEach(c => { pts.add(clamp(c.start, 0, text.length)); pts.add(clamp(c.end, 0, text.length)); }); const b = Array.from(pts).sort((x, y) => x - y); let out = '';
  for (let i = 0; i < b.length - 1; i++) {
    const s = b[i], e = b[i + 1]; if (s === e) continue; const seg = text.slice(s, e); const cov = cls.filter(c => c.start <= s && c.end >= e); const ct = cites.find(c => c.start <= s && c.end >= e);
    if (!cov.length && !ct) { out += markQ(seg, query); continue; }
    if (!cov.length) { out += `<mark class="ct" role="button" tabindex="0" data-act="nav" data-href="${ct.href}" title="Citation — open citation audit">${markQ(seg, query)}</mark>`; continue; }
    const prim = cov.find(c => c.id === focusId) || cov[0]; out += `<mark class="cl ${prim.id === focusId ? 'focus' : ''} ${prim.rv ? 'rv' : ''} ${prim.cf ? 'cf' : ''}" role="button" tabindex="0" data-act="nav" data-href="${prim.href}" data-hover="${esc(cov.map(c => c.id).join(','))}" aria-label="Claim ${esc(prim.id)}">${markQ(seg, query)}</mark>`;
  }
  return out;
}
function sheetHtml(C, X, d, page, focusId, query) {
  const pg = d.pages[page - 1]; if (!pg) return '';
  return `<article class="sheet" aria-label="${esc(docName(d))}, page ${page}"><span class="pn">PAGE ${pad(page)}</span>${pg.paras.map((p, i) => {
    const cls = C.claims.filter(c => c.sourceDocId === d.id && c.page === page && c.para === i + 1).map(c => { const inf = X.info(c); return { id: c.id, start: c.start, end: c.end, rv: inf.reviewed, cf: inf.inConflict, href: X.href(c) }; });
    const cites = C.citations.filter(x => x.docId === d.id && x.page === page && x.para === i + 1 && x.kind === 'CITATION').map(x => ({ start: x.start, end: x.end, href: caseHref(C, 'citations?cit=' + x.id) }));
    const hasEv = C.evidence.some(e => e.sourceDocId === d.id && e.page === page && e.para === i + 1);
    const foc = cls.some(c => c.id === focusId);
    return `<p class="${hasEv ? 'hasev' : ''}" ${foc ? 'data-focus="1"' : ''} id="p${page}-${i + 1}"><span class="gut">¶${i + 1}</span>${paraHtml(p.text, cls, focusId, query, cites)}</p>`; }).join('') || '<p class="muted">This page has no extractable text.</p>'}</article>`;
}
function DocViewerView(C, docId, q) {
  const X = derive(C); const d = X.doc(docId); if (!d) return { title: 'Document not found', crumbs: crumbsFor(C, ['Documents', caseHref(C, 'documents')], ['Not found']), html: `<div class="page narrow">${empty({ icon: 'file', title: 'Document not found', text: 'This document is not part of the case.', action: `<div style="margin-top:10px">${linkBtn('Back to documents', caseHref(C, 'documents'), { cls: 'primary' })}</div>` })}</div>` };
  if (d.kind === 'transcript') return HearingView(C, { doc: d.id, claim: q.claim });
  const focus = q.claim && X.claim(q.claim); let page = +(q.page || 1); if (focus && focus.sourceDocId === d.id) page = focus.page; page = clamp(page || 1, 1, d.pageCount);
  UI.dv = { caseId: C.id, docId, page, focusId: focus && focus.sourceDocId === d.id ? focus.id : null };
  const docs = C.documents;
  const left = `<aside class="dv-l" aria-label="Documents"><div class="dv-h">Documents</div>${docs.filter(x => x.kind === 'document').map(x => `<a class="dv-doc" href="${docHref(C, x)}" ${x.id === d.id ? 'aria-current="true"' : ''}>${icon('file', 16)}<span style="min-width:0"><span class="trunc" style="display:block;font-weight:${x.id === d.id ? 600 : 500}">${esc(docName(x))}</span><span class="faint" style="font-size:12px">${esc(x.category)} · ${plural(x.pageCount, 'page')}</span></span></a>`).join('')}${docs.some(x => x.kind === 'transcript') ? `<div class="dv-h">Hearing transcripts</div>${docs.filter(x => x.kind === 'transcript').map(x => `<a class="dv-doc" href="${docHref(C, x)}">${icon('mic', 16)}<span style="min-width:0"><span class="trunc" style="display:block;font-weight:500">${esc(docName(x))}</span><span class="faint" style="font-size:12px">${plural(x.statementCount, 'statement')}</span></span></a>`).join('')}` : ''}</aside>`;
  const bar = `<div class="dv-bar"><div style="min-width:0;flex:1 1 100%"><div class="trunc" style="font-weight:620">${esc(docName(d))}</div><div class="faint" style="font-size:12px"><span class="mono">${d.id}</span> · ${esc(d.category)} · ${plural(d.pageCount, 'page')} · ${badge(docStatus(d), d.status)}</div></div>
    <div class="row"><a class="btn sm" ${page > 1 ? `href="${caseHref(C, 'documents/' + d.id + '?page=' + (page - 1))}"` : 'aria-disabled="true" style="opacity:.4;pointer-events:none"'} aria-label="Previous page">${icon('left', 14)}</a><span class="mono" style="font-size:12.5px">Page ${page} / ${d.pageCount}</span><a class="btn sm" ${page < d.pageCount ? `href="${caseHref(C, 'documents/' + d.id + '?page=' + (page + 1))}"` : 'aria-disabled="true" style="opacity:.4;pointer-events:none"'} aria-label="Next page">${icon('right', 14)}</a></div>
    <div class="searchin" style="width:190px">${icon('search', 14)}<input type="text" data-in="docq" placeholder="Find in document" aria-label="Find in document" value="${esc(UI.docQ)}" style="height:30px"></div><button class="btn sm" data-act="focus-mode" title="Focus mode">${icon('maximize', 14)}Focus mode</button></div><div class="hlkey" style="padding:6px 18px 0"><span><i style="color:var(--hl-line)"></i>Claim</span><span><i style="color:var(--gold)"></i>Evidence paragraph</span><span><i style="color:var(--warn)"></i>Potential conflict</span><span><i style="color:var(--accent);border-bottom-style:dotted"></i>Citation</span><span><i style="color:var(--ok)"></i>Reviewed</span></div><div id="matchbar" class="faint" style="font-size:12.5px;padding:0 18px"></div>`;
  return { title: docName(d), crumbs: crumbsFor(C, ['Documents', caseHref(C, 'documents')], [docName(d)]), noPadding: true, mount() { dvMatches(); }, html: `<div class="dv">${left}<div class="dv-c">${bar}<div class="dv-scroll" id="dvscroll"><div id="sheetwrap">${sheetHtml(C, X, d, page, UI.dv.focusId, UI.docQ)}</div></div></div><aside class="dv-r" id="dvright" aria-label="Intelligence">${dvRight(C, X, d, page, focus)}</aside></div>` };
}
function dvRight(C, X, d, page, focus) {
  const cl = C.claims.filter(c => c.sourceDocId === d.id); const onPage = cl.filter(c => c.page === page), other = cl.filter(c => c.page !== page); const ev = C.evidence.filter(e => e.sourceDocId === d.id); const cit = C.citations.filter(x => x.docId === d.id); const en = d.entities || { people: [], locations: [], dates: [] };
  const card = c => { const inf = X.info(c); return `<a class="cardbtn" href="${X.href(c)}" ${focus && focus.id === c.id ? 'aria-current="true"' : ''}><div class="row between"><span class="idcell">${c.id}</span>${badge(inf.inConflict ? 'CONFLICT' : inf.status)}</div><div style="margin-top:5px;font-size:13px">${esc(trunc(c.text, 120))}</div><div class="faint" style="font-size:12px;margin-top:4px">Page ${c.page} · ¶${c.para} · ${plural(inf.evCount, 'linked item')}</div></a>`; };
  const pii = d.entities && d.entities.pii ? Object.entries(d.entities.pii).filter(([, n]) => n > 0) : [];
  return `${focus && focus.sourceDocId === d.id ? `<div style="padding:14px;border-bottom:1px solid var(--line)"><div class="row between"><span class="lbl">Selected claim</span>${aiTag('claim', focus.id)}</div><div class="idcell" style="margin:6px 0 2px">${focus.id}</div><p style="font-size:13.5px">${esc(focus.text)}</p><dl class="kv" style="grid-template-columns:80px 1fr;margin:10px 0;font-size:12.5px"><dt>Source</dt><dd>${esc(X.src(focus))}</dd><dt>Speaker</dt><dd>${esc(focus.speaker || '—')}</dd><dt>Extraction</dt><dd>${Math.round(focus.confidence * 100)}% confidence</dd></dl>${linkBtn('View claim detail', caseHref(C, 'claims/' + focus.id), { cls: 'primary sm' })}</div>` : ''}
  <div class="dv-h">Claims on this page (${onPage.length})</div><div style="padding:0 12px">${onPage.map(card).join('') || '<p class="faint" style="padding:4px 2px 10px;font-size:13px">No claims were extracted from this page.</p>'}</div>
  ${other.length ? `<details style="padding:0 12px 6px"><summary class="dv-h" style="cursor:pointer;padding-left:2px">Other pages (${other.length})</summary>${other.map(card).join('')}</details>` : ''}
  <div class="dv-h">Evidence from this document (${ev.length})</div><div style="padding:0 12px">${ev.map(e => `<button class="cardbtn" data-act="ev-open" data-id="${e.id}"><span class="idcell">${e.id}</span> <span class="tag">${esc(EVIDENCE_LABEL[e.type] || e.type)}</span><div style="font-size:12.5px;margin-top:4px">${esc(trunc(e.description, 100))}</div></button>`).join('') || '<p class="faint" style="font-size:13px;padding:0 2px 10px">None identified.</p>'}</div>
  ${cit.length ? `<div class="dv-h">Citations (${cit.length})</div><div style="padding:0 12px">${cit.map(x => `<a class="cardbtn" href="${caseHref(C, 'citations')}"><span class="mono" style="font-size:12px">${esc(trunc(x.citationText, 70))}</span><div style="margin-top:4px">${badge(x.result === 'POTENTIALLY_RELEVANT' ? 'ACCEPTED' : 'NEEDS_REVIEW', CITE_LABEL[x.result])}</div></a>`).join('')}</div>` : ''}
  <div class="dv-h">Entities</div><div style="padding:0 14px 16px" class="col" style="gap:8px"><div class="chips">${en.people.map(p => `<span class="tag">${esc(p)}</span>`).join('') || '<span class="faint">No people detected</span>'}</div><div class="chips" style="margin-top:8px">${en.locations.map(p => `<span class="tag">${icon('pin', 11)}${esc(p)}</span>`).join('')}</div><div class="chips" style="margin-top:8px">${en.dates.map(p => `<span class="tag">${icon('cal', 11)}${esc(p)}</span>`).join('')}</div>${pii.length ? `<div class="note warn" style="margin-top:10px">${icon('lock', 13)}<span>Possible personal data: ${pii.map(([k, n]) => n + ' ' + k).join(', ')}. Redaction applies to reports only.</span></div>` : ''}</div>`;
}
const CITE_LABEL = { POTENTIALLY_RELEVANT: 'Potentially relevant', WEAK_RELEVANCE: 'Weak relevance', MISSING_CITATION: 'No authority identified', UNRESOLVED: 'Unable to map' };
ACT.nav = el => go(el.dataset.href);
ACT['focus-mode'] = () => { document.body.classList.add('focus'); toast('Focus mode on. Press Esc to exit.', 'ok'); };
INPUT.docq = t => {
  UI.docQ = t.value; const C = currentCaseSafe(); if (!C || !UI.dv) return; const X = derive(C), d = X.doc(UI.dv.docId); if (!d) return; const w = $('#sheetwrap'); if (w) w.innerHTML = sheetHtml(C, X, d, UI.dv.page, UI.dv.focusId, UI.docQ); dvMatches();
};
function dvMatches() {
  const el = $('#matchbar'); const C = currentCaseSafe(); if (!el || !C || !UI.dv) return; const q = UI.docQ.trim(); if (q.length < 2) { el.innerHTML = ''; return; }
  const d = C.documents.find(x => x.id === UI.dv.docId); const re = new RegExp(q.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'gi'); const per = d.pages.map((p, i) => [i + 1, (p.paras.map(x => x.text).join(' ').match(re) || []).length]).filter(x => x[1]);
  el.innerHTML = per.length ? `<div class="row wrap" style="padding:6px 0">Matches: ${per.map(([p, n]) => `<a class="tag" href="${caseHref(C, 'documents/' + d.id + '?page=' + p)}">p${p} · ${n}</a>`).join('')}</div>` : '<div style="padding:6px 0">No matches in this document.</div>';
}

/* ---------- hearing workstation ---------- */
const tsSec = s => { const p = String(s || '').split(':').map(Number); if (p.some(isNaN)) return null; return p.length === 3 ? p[0] * 3600 + p[1] * 60 + p[2] : p.length === 2 ? p[0] * 60 + p[1] : null; };
function hearingUpload(C, hasT) {
  if (C.status === 'ARCHIVED') return '';
  return `<section class="panel" style="margin-bottom:18px"><div class="ph"><h2>${hasT ? 'Add another transcript' : 'Upload a hearing transcript'}</h2></div><div class="pb"><div class="fgrid" style="margin-bottom:14px"><div class="field"><label for="hd">Hearing date</label><input id="hd" type="date"></div><div class="field"><label for="hn">Hearing number</label><input id="hn" type="text" maxlength="20" placeholder="e.g. 3"></div></div>
  <div class="grid2"><div class="drop" data-drop="trdrop" data-case="${C.id}">${icon('upload', 22)}<b>Upload transcript</b>${btn('Browse files', 'data-act="pick-files" data-target="trfile"', { cls: 'primary sm' })}<span class="mono faint" style="font-size:12px">PDF · DOCX · TXT</span><input id="trfile" type="file" accept=".pdf,.docx,.txt,.md" class="hide" data-change="trfile" data-case="${C.id}"></div>
  <div class="field"><label for="trtext">…or paste transcript text</label><textarea id="trtext" style="min-height:120px" placeholder="10:06:18 WITNESS 1: Text of the statement, one line per speaker turn."></textarea><div class="row" style="justify-content:flex-end;margin-top:6px">${btn('Add pasted transcript', `data-act="add-pasted" data-case="${C.id}"`, { cls: 'sm' })}</div></div></div>
  <p class="faint" style="font-size:12.5px;margin-top:10px">Lines like “10:06:18 PW-3: statement” are parsed into speakers, questions and answers. If the transcript is missing, analysis still runs on the documents.</p><div id="uploadq" class="col" style="gap:8px;margin-top:12px"></div></div></section>`;
}
INPUT.trfile = t => { ingest(t.dataset.case, t.files, { kind: 'transcript', hearingDate: ($('#hd') || {}).value || null, hearingNumber: ($('#hn') || {}).value || null }); t.value = ''; };
INPUT.trdrop = t => ingest(t.dataset.case, t.files, { kind: 'transcript', hearingDate: ($('#hd') || {}).value || null, hearingNumber: ($('#hn') || {}).value || null });
ACT['add-pasted'] = async el => {
  const txt = ($('#trtext') || {}).value || ''; if (txt.trim().length < 10) { toast('Paste the transcript text first.', 'warn'); return; }
  try { const d = await Data.addTranscriptText(el.dataset.case, { text: txt, hearingDate: $('#hd').value || null, hearingNumber: $('#hn').value || null }); toast(d.statementCount ? `Transcript added: ${plural(d.statementCount, 'statement')} found.` : 'Transcript added, but no timestamped statements were recognised.', d.statementCount ? 'ok' : 'warn'); go(caseHref({ id: el.dataset.case }, 'hearing?doc=' + d.id)); render(); } catch (e) { toast(e.message || 'Unable to add the transcript.', 'bad'); }
};
function HearingView(C, q) {
  if (accessOf(C) === 'hearing') return TranscriptWorkspace(C, q);
  const X = derive(C); const trs = C.documents.filter(d => d.kind === 'transcript');
  const head = `<div class="pagehead"><div><h1>Hearings</h1><p class="sub">Transcripts are split into speakers and statements. Claims and uncertainty language are linked back to the exact statement.</p></div></div>`;
  if (!trs.length) return { title: 'Hearings', crumbs: crumbsFor(C, ['Hearings']), mount: paintQueue, html: `<div class="page narrow">${head}${hearingsPanel(C)}${hearingUpload(C, false)}${empty({ icon: 'mic', title: 'No hearing transcript', text: 'Upload a hearing transcript to add speaker-level statements and timestamps to the analysis.' })}</div>` };
  const t = trs.find(x => x.id === q.doc) || trs[0]; const focus = q.claim && X.claim(q.claim);
  const stm = []; t.pages.forEach((pg, pi) => pg.paras.forEach((p, i) => stm.push({ ...p, page: pi + 1, para: i + 1 })));
  UI.hv.doc = t.id; UI.hv.focus = focus ? focus.id : null;
  const spk = {}; stm.forEach(s => { spk[s.speaker] = spk[s.speaker] || { n: 0, role: s.role }; spk[s.speaker].n++; });
  const tabs = trs.length > 1 ? `<div class="chips" style="margin-bottom:12px">${trs.map(x => `<a class="chip" aria-pressed="${x.id === t.id}" href="${caseHref(C, 'hearing?doc=' + x.id)}">${esc(docName(x))}</a>`).join('')}</div>` : '';
  return { title: 'Hearings', crumbs: crumbsFor(C, ['Hearings']), mount() { hvMount(); paintQueue(); }, noPadding: false,
    html: `<div class="page wide">${head}${hearingsPanel(C)}${tabs}<div class="row wrap between" style="margin-bottom:12px"><div class="muted"><b style="color:var(--text)">${esc(docName(t))}</b> · ${plural(stm.length, 'statement')}${t.hearingDate ? ' · Hearing ' + esc(t.hearingNumber || '') + ' on ' + esc(t.hearingDate) : ''}</div><div class="row">${btn('Focus mode', 'data-act="focus-mode"', { icon: 'maximize', cls: 'sm' })}</div></div>
    <div class="hv" id="hvgrid"><aside><div class="dv-h">Speakers</div>${Object.entries(spk).map(([n, s]) => `<button class="dv-doc" data-act="spk" data-s="${esc(n)}" aria-current="${UI.hv.spk === n}">${icon(s.role === 'Judge' ? 'scale' : s.role === 'Counsel' ? 'user' : 'mic', 15)}<span style="min-width:0"><span class="trunc" style="display:block;font-weight:550">${esc(n)}</span><span class="faint" style="font-size:12px">${esc(s.role || '')} · ${s.n}</span></span></button>`).join('')}${UI.hv.spk ? `<div style="padding:10px 14px">${btn('Show all speakers', 'data-act="spk" data-s=""', { cls: 'sm' })}</div>` : ''}</aside>
    <div id="stmts"></div><aside id="hvright"></aside></div><div class="tlbar"><div class="row between"><b style="font-size:13px">Hearing timeline</b><span class="faint" style="font-size:12px">Select a marker to jump to the statement</span></div><div id="hvtl"></div></div>${hearingUpload(C, true)}</div>` };
}
function hvMount() {
  const C = currentCaseSafe(); if (!C) return; const X = derive(C); const t = C.documents.find(d => d.id === UI.hv.doc); if (!t) return;
  const stm = []; t.pages.forEach((pg, pi) => pg.paras.forEach((p, i) => stm.push({ ...p, page: pi + 1, para: i + 1 })));
  const claimsBy = {}; C.claims.filter(c => c.sourceDocId === t.id).forEach(c => { (claimsBy[c.page + ':' + c.para] = claimsBy[c.page + ':' + c.para] || []).push(c); });
  const shown = stm.map((s, i) => ({ ...s, i })).filter(s => !UI.hv.spk || s.speaker === UI.hv.spk); const vis = shown.slice(0, UI.hv.max);
  $('#stmts').innerHTML = vis.map(s => { const cl = claimsBy[s.page + ':' + s.para] || []; const unc = cl.some(c => c.uncertainty >= 60) || UNCERT.test(s.text); const cls = cl.map(c => { const inf = X.info(c); return { id: c.id, start: c.start, end: c.end, rv: inf.reviewed, cf: inf.inConflict, href: X.href(c) }; }); const foc = cl.some(c => c.id === UI.hv.focus);
    return `<div class="stmt ${s.qkind === 'QUESTION' ? 'q' : ''} ${foc ? 'focus' : ''}" id="st${s.i}" ${foc ? 'data-focus="1"' : ''}><div><div class="mono faint" style="font-size:12px">${esc(s.ts || '')}</div></div><div><div class="who">${esc(s.speaker)}${s.qkind === 'QUESTION' ? ' <span class="faint" style="font-weight:400">asks</span>' : ''}</div><div class="body">${paraHtml(s.text, cls, UI.hv.focus, '')}</div><div class="row wrap" style="margin-top:6px;gap:6px">${cl.map(c => `<a class="tag" href="${X.href(c)}">${c.id}</a>`).join('')}${unc ? `<span class="badge warn" title="Hedged wording is recorded for context only. It says nothing about honesty.">${icon('help', 12)}Uncertainty language</span>` : ''}${cl.some(c => X.info(c).inConflict) ? `<span class="badge bad">${icon('warn', 12)}Potential conflict</span>` : ''}</div></div></div>`; }).join('') + (shown.length > vis.length ? `<div style="padding:14px;text-align:center">${btn(`Show ${Math.min(120, shown.length - vis.length)} more`, 'data-act="hv-more"', { cls: 'sm' })}</div>` : '') || '<div class="pb muted">No statements were recognised in this transcript. Lines should start with a timestamp and speaker, e.g. “10:06:18 PW-3: …”.</div>';
  const cls = C.claims.filter(c => c.sourceDocId === t.id); const focus = UI.hv.focus && X.claim(UI.hv.focus);
  const evs = new Map(); cls.forEach(c => X.info(c).strong.forEach(r => evs.set(r.ev.id, r.ev)));
  $('#hvright').innerHTML = `${focus ? `<div style="padding:14px;border-bottom:1px solid var(--line)"><div class="row between"><span class="lbl">Selected claim</span>${aiTag('claim', focus.id)}</div><div class="idcell" style="margin:6px 0 2px">${focus.id}</div><p style="font-size:13.5px">${esc(focus.text)}</p>${X.info(focus).strong.slice(0, 4).map(r => `<div class="faint" style="font-size:12.5px;margin-top:3px">${esc(r.rel.relationship.toLowerCase())}: ${esc(trunc(r.ev.description, 60))}</div>`).join('')}<div style="margin-top:10px">${linkBtn('View claim detail', caseHref(C, 'claims/' + focus.id), { cls: 'primary sm' })}</div></div>` : ''}<div class="dv-h">Claims (${cls.length})</div><div style="padding:0 12px">${cls.map(c => { const inf = X.info(c); return `<a class="cardbtn" href="${X.href(c)}" ${focus && focus.id === c.id ? 'aria-current="true"' : ''}><div class="row between"><span class="idcell">${c.id}</span>${badge(inf.inConflict ? 'CONFLICT' : inf.status)}</div><div style="font-size:12.5px;margin-top:4px">${esc(trunc(c.text, 90))}</div></a>`; }).join('') || '<p class="faint" style="font-size:13px;padding:0 2px">Run analysis to extract claims.</p>'}</div><div class="dv-h">Linked evidence (${evs.size})</div><div style="padding:0 12px 14px">${Array.from(evs.values()).map(e => `<button class="cardbtn" data-act="ev-open" data-id="${e.id}"><span class="idcell">${e.id}</span> <span class="tag">${esc(EVIDENCE_LABEL[e.type] || e.type)}</span></button>`).join('') || '<p class="faint" style="font-size:13px;padding:0 2px">None linked.</p>'}</div>`;
  hvTimeline(C, X, t, stm, claimsBy);
}
function hvTimeline(C, X, t, stm, claimsBy) {
  const el = $('#hvtl'); if (!el) return; const pts = stm.map((s, i) => ({ i, s, sec: tsSec(s.ts) })).filter(p => p.sec != null); if (pts.length < 2) { el.innerHTML = `<p class="faint" style="padding:10px 0">Not enough timestamps to draw a timeline.</p>`; return; }
  const min = Math.min(...pts.map(p => p.sec)), max = Math.max(...pts.map(p => p.sec)), span = Math.max(1, max - min); const W = 1000, x = s => 30 + (s - min) / span * (W - 60);
  const lanes = [['Question', 22], ['Claim', 46], ['Uncertainty', 70], ['Potential conflict', 94]]; const mk = [];
  pts.forEach(p => { const cl = claimsBy[(Math.floor(p.i / 14) + 1) + ':' + (p.i % 14 + 1)] || []; if (p.s.qkind === 'QUESTION') mk.push([0, p]); if (cl.length) mk.push([1, p]); if (cl.some(c => c.uncertainty >= 60) || UNCERT.test(p.s.text)) mk.push([2, p]); if (cl.some(c => X.info(c).inConflict)) mk.push([3, p]); });
  const col = ['var(--idle)', 'var(--accent)', 'var(--warn)', 'var(--bad)']; const used = [...new Set(mk.map(m => m[0]))].sort();
  const ticks = 5; let tk = ''; for (let i = 0; i <= ticks; i++) { const s = min + span * i / ticks; tk += `<text x="${x(s)}" y="118" text-anchor="middle" font-size="10" font-family="var(--mono)" fill="var(--text-3)">${pad(Math.floor(s / 3600))}:${pad(Math.floor(s % 3600 / 60))}:${pad(Math.round(s % 60))}</text>`; }
  el.innerHTML = `<svg viewBox="0 0 ${W} 126" role="img" aria-label="Hearing timeline" style="height:auto">${lanes.map((l, i) => `<line x1="30" x2="${W - 30}" y1="${l[1]}" y2="${l[1]}" stroke="var(--line)" stroke-dasharray="2 4"/><text x="0" y="${l[1] + 3}" font-size="9" fill="var(--text-3)" ${used.includes(i) ? '' : 'opacity=".4"'} font-family="var(--font)"></text>`).join('')}${mk.map(m => `<circle cx="${x(m[1].sec)}" cy="${lanes[m[0]][1]}" r="5.5" fill="${col[m[0]]}" stroke="var(--surface)" stroke-width="2" style="cursor:pointer" role="button" tabindex="0" data-act="jump-stmt" data-i="${m[1].i}"><title>${esc(m[1].s.ts + ' ' + m[1].s.speaker + ': ' + trunc(m[1].s.text, 60))}</title></circle>`).join('')}${tk}</svg><div class="legend">${lanes.map((l, i) => used.includes(i) ? `<span><i style="background:${col[i]}"></i>${l[0]}</span>` : '').join('')}</div>`;
}
ACT.spk = el => { UI.hv.spk = el.dataset.s || null; UI.hv.max = 120; render(); };
ACT['hv-more'] = () => { UI.hv.max += 120; hvMount(); };
ACT['jump-stmt'] = el => { let i = +el.dataset.i; const n = $('#st' + i); if (!n) { UI.hv.max = Math.max(UI.hv.max, i + 1); hvMount(); } const t = $('#st' + i); if (t) { t.scrollIntoView({ block: 'center', behavior: prefs().reduceMotion ? 'auto' : 'smooth' }); t.classList.add('focus'); setTimeout(() => t.classList.remove('focus'), 1800); } };

function paintDocsSimple() { paintDocs(); }
