"""Reference-integrity checks for the EvidenceConflictAgent.

Unlike the CaseUnderstandingAgent (which has to verify a *quote* against raw
text), this agent's inputs are already-structured, already-sourced objects
(Claim, EvidenceItem). So "provenance" here means: every id the model uses
must resolve to something it was actually given, and the SourceReference
attached to any output is always copied from that resolved object — never
restated or re-generated by the model. These functions are the only place
that is allowed to declare a reference valid.
"""
from __future__ import annotations

from dataclasses import dataclass

from ..case_understanding.schemas import Claim
from .schemas import EvidenceItem


@dataclass(frozen=True)
class ResolutionResult:
    ok: bool
    reason: str = ""


def resolve_claim(claim_id: str | None, claims_by_id: dict[str, Claim]) -> tuple[Claim | None, ResolutionResult]:
    if not claim_id:
        return None, ResolutionResult(False, "claim_id was not supplied.")
    claim = claims_by_id.get(claim_id)
    if claim is None:
        return None, ResolutionResult(
            False, f"claim_id {claim_id!r} does not match any claim supplied to this run."
        )
    return claim, ResolutionResult(True)


def resolve_evidence(
    evidence_id: str | None, evidence_by_id: dict[str, EvidenceItem]
) -> tuple[EvidenceItem | None, ResolutionResult]:
    if not evidence_id:
        return None, ResolutionResult(False, "evidence_id was not supplied.")
    evidence = evidence_by_id.get(evidence_id)
    if evidence is None:
        return None, ResolutionResult(
            False, f"evidence_id {evidence_id!r} does not match any evidence supplied to this run."
        )
    return evidence, ResolutionResult(True)


def resolve_side(
    side: dict,
    claims_by_id: dict[str, Claim],
    evidence_by_id: dict[str, EvidenceItem],
) -> tuple[dict | None, ResolutionResult]:
    """Resolve one side of a proposed conflict. Returns a dict with the
    resolved id/kind/source ready to build a ConflictSide, or a failure
    reason if the reference does not check out.
    """
    claim_id = side.get("claim_id")
    evidence_id = side.get("evidence_id")

    if claim_id and evidence_id:
        return None, ResolutionResult(False, "A conflict side named both a claim_id and an evidence_id.")
    if not claim_id and not evidence_id:
        return None, ResolutionResult(False, "A conflict side named neither a claim_id nor an evidence_id.")

    if claim_id:
        claim, res = resolve_claim(claim_id, claims_by_id)
        if not res.ok:
            return None, res
        return {"claim_id": claim_id, "source": claim.source}, ResolutionResult(True)

    evidence, res = resolve_evidence(evidence_id, evidence_by_id)
    if not res.ok:
        return None, res
    return {"evidence_id": evidence_id, "source": evidence.source}, ResolutionResult(True)


def enforce_all_references_resolve(
    relationships: list, conflicts: list, gaps: list,
    claims_by_id: dict[str, Claim], evidence_by_id: dict[str, EvidenceItem],
) -> list[str]:
    """Final safety net: re-walk every already-constructed finding and
    confirm every id it carries still resolves against the supplied input.
    Returns violation messages; callers should treat any non-empty result as
    a bug, since the primary construction path should never let an
    unresolved reference through in the first place.
    """
    violations: list[str] = []

    for rel in relationships:
        if rel.claim_id not in claims_by_id:
            violations.append(f"relationship {rel.relationship_id}: claim_id {rel.claim_id!r} no longer resolves.")
        if rel.evidence_id not in evidence_by_id:
            violations.append(f"relationship {rel.relationship_id}: evidence_id {rel.evidence_id!r} no longer resolves.")

    for conflict in conflicts:
        for label, side in (("side_a", conflict.side_a), ("side_b", conflict.side_b)):
            if side.claim_id and side.claim_id not in claims_by_id:
                violations.append(f"conflict {conflict.conflict_id}: {label} claim_id {side.claim_id!r} no longer resolves.")
            if side.evidence_id and side.evidence_id not in evidence_by_id:
                violations.append(f"conflict {conflict.conflict_id}: {label} evidence_id {side.evidence_id!r} no longer resolves.")

    for gap in gaps:
        if gap.claim_id not in claims_by_id:
            violations.append(f"support_gap {gap.gap_id}: claim_id {gap.claim_id!r} no longer resolves.")
        for eid in gap.related_evidence_ids:
            if eid not in evidence_by_id:
                violations.append(f"support_gap {gap.gap_id}: related evidence_id {eid!r} no longer resolves.")

    return violations
